### ISSUE TITLE
Could you provide exports of the VBA modules?

### ISSUE THREAD

**Issue by sancarn** [thetrik/VbTrickTimer#1]
Hi Trick,

When I open the .doc in word I receive the following error:

`Word was unable to read this document, it may be corrupt.`

I downloaded the VB6 class and tried it, but the callback function was never called so I'm unsure if this is caused by a win10 issue, excel2016 issueor a vb6-->vba issue.

Finally, I see you're accessing EbMode from memory? Does this mean you can also access EbExecuteLine from memory?

**Comment by thetrik** [comment]
Hello. Thank you for the response. Can you please tell me what does **SearchEbMode** return?

**Comment by sancarn** [comment]
Hi Trick,

Terribly sorry for not getting back sooner.

SearchEbMode returns `396329616`

**Comment by sancarn** [comment]
Hi Trick,

So I've looked into it some more and I think I know what's going on now. When I originally tried this I didn't do it within a UserForm, I put the macros within the `ThisWorkbook` document object itself:

```vb
Private WithEvents cTimer As CTrickTimer

Sub AddTimer()
    Set cTimer = New CTrickTimer
    cTimer.Tag = "WorkbookTick"
    cTimer.Interval = 100
End Sub

Sub RemoveTimer()
    Set cTimer = Nothing
End Sub

Private Sub cTimer_Tick()
    'Change color of cell A1
    Sheet1.Range("A1").Interior.Color = RGB(Math.Rnd() * 255, Math.Rnd() * 255, Math.Rnd() * 255)
End Sub
```

Calling `AddTimer()` in this case doesn't cause `cTimer_Tick` to be called.

However when I recreate your userform example, it does call `cTimer_Tick` of `CTimerEventRouter` class.
